### PR TITLE
Preseed

### PR DESCRIPTION
**Pull request by RudoRoemer**
Dear all, 

this version introduces routines SRANDOM5() and DRANDOM5() which use a combination of Seed, Width, Energy, HubDis and RimDis to compute 5 seeds and initialize a Mersenne twister (MT95.f90) with such a seed. I have checked that this seems to avoid repeated random numbers. It also means we do not need to change the names for our .raw files.

Jie, can you please have a quick check that all works before we merge?

### CODE REVIEW

**Review by liujie940228 — COMMENTED** [review]
in src/inout.f90, Why delete the case of Energy<0? Maybe 268 line to 275 line.

**Review by liujie940228 — COMMENTED** [review]
in src/inout.f90, Why delete the case of Energy<0? Maybe 268 line to 275 line.

In src/main_LSD.f90, I am confused about the use of drandval=DRANDOM5(ISSeed), actually, the ISSeed doesn't be used and generated a random number in interval [0,1] with seed called dRet(a parameter just be defined as real(kind=rkind):: dRet )

**Comment by RudoRoemer** [comment]
I updated the preseed branch to take into account these issues raised by Jie.

**Comment by RudoRoemer** [comment]
Jie, DRANDOM5() as part of MT95 uses a number of internal "states" which each subroutine accessed via variables "global" to the MT95 module. So the "seed" (state) is used, but not explicitely.

**Pull request merged**
